
from fastapi import APIRouter, Form, UploadFile, File, HTTPException
import io
import os
import tempfile
import uuid
from PIL import Image
from pydantic import BaseModel
from typing import Optional
from services.firebase_service import upload_file_to_firebase

# Import the new google-genai library
try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None

router = APIRouter()

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

# Initialize client if available
client = None
if genai and GOOGLE_API_KEY:
    client = genai.Client(api_key=GOOGLE_API_KEY)

class ImageGenerationResponse(BaseModel):
    success: bool
    output: Optional[str] = None # Public image URL
    error: Optional[str] = None
    metadata: Optional[dict] = None

@router.post("", response_model=ImageGenerationResponse)
async def generate_image(
    prompt: str = Form(...),
    image: UploadFile = File(None),
    workflow_id: Optional[str] = Form(None),
    filename: Optional[str] = Form(None)
):
    """
    Generates or edits an image using Google's Gemini 2.5 Flash (Nano Banana) model.
    Uses the new `google-genai` SDK.
    Returns JSON with a public Firebase image URL.
    """
    if not genai:
        raise HTTPException(status_code=500, detail="The 'google-genai' library is not installed. Please install it.")
    if not client:
        raise HTTPException(status_code=500, detail="Google GenAI client not initialized. Check GOOGLE_API_KEY.")

    try:
        model_name = "gemini-2.5-flash-image"
        
        # Prepare contents
        contents = [prompt]
        
        if image:
            image_bytes = await image.read()
            try:
                pil_image = Image.open(io.BytesIO(image_bytes))
                contents.append(pil_image)
            except Exception as e:
                return ImageGenerationResponse(success=False, error=f"Invalid image file: {str(e)}")

        # Call the model
        response = client.models.generate_content(
            model=model_name,
            contents=contents
        )
        
        # Extract response
        generated_image_bytes = None
        
        if response.candidates:
             for candidate in response.candidates:
                 if candidate.content and candidate.content.parts:
                     for part in candidate.content.parts:
                         if part.inline_data:
                             generated_image_bytes = part.inline_data.data
                             break
        
        if not generated_image_bytes:
            # Check for text fallback
            text = response.text if hasattr(response, 'text') else "No output."
            return ImageGenerationResponse(success=False, error="No image generated.", metadata={"details": text})

        # Upload generated bytes to Firebase and return a public URL.
        resolved_workflow_id = workflow_id or str(uuid.uuid4())
        resolved_filename = filename or f"generated_{resolved_workflow_id}.png"
        temp_file_path = os.path.join(tempfile.gettempdir(), f"{uuid.uuid4()}.png")
        with open(temp_file_path, "wb") as temp_file:
            temp_file.write(generated_image_bytes)

        try:
            image_url = upload_file_to_firebase(
                temp_file_path,
                resolved_workflow_id,
                resolved_filename
            )
        finally:
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)

        return ImageGenerationResponse(
            success=True,
            output=image_url,
            metadata={
                "model": model_name,
                "content_type": "image/png",
                "workflow_id": resolved_workflow_id,
                "filename": resolved_filename,
                "path": f"workflow/{resolved_workflow_id}/{resolved_filename}"
            }
        )

    except Exception as e:
        return ImageGenerationResponse(success=False, error=f"GenAI Error: {str(e)}")
