import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";

import { WorkflowProvider } from "@/context/WorkflowContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "n8n Agent Creator",
  description: "Generated by create next app",
};

import { LiveStatusProvider } from "@/context/LiveStatusContext";
import { GlobalLiveStatus } from "@/components/GlobalLiveStatus";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WorkflowProvider>
          <LiveStatusProvider>
            <div className="flex min-h-screen bg-zinc-50 dark:bg-zinc-950">
              <Sidebar />
              <main className="flex-1 overflow-y-auto">
                {children}
              </main>
              <GlobalLiveStatus />
            </div>
          </LiveStatusProvider>
        </WorkflowProvider>
      </body>
    </html>
  );
}
